// aspectRecipes.js

export const FULL_ASPECT_RECIPES = {
  aer: [],
  terra: [],
  ignis: [],
  aqua: [],
  ordo: [],
  perditio: [],
  vacuos: ["aer", "perditio"],
  lux: ["aer", "ignis"],
  potentia: ["ordo", "ignis"],
  motus: ["aer", "ordo"],
  gelum: ["ignis", "perditio"],
  vitreus: ["terra", "ordo"],
  victus: ["aqua", "terra"],
  venenum: ["aqua", "perditio"],
  permutatio: ["perditio", "ordo"],
  metallum: ["terra", "vitreus"],
  mortuus: ["victus", "perditio"],
  volatus: ["aer", "motus"],
  tenebrae: ["vacuos", "lux"],
  spiritus: ["victus", "mortuus"],
  sano: ["ordo", "victus"],
  iter: ["motus", "terra"],
  alienis: ["vacuos", "tenebrae"],
  praecantatio: ["vacuos", "potentia"],
  auram: ["praecantatio", "aer"],
  vitium: ["praecantatio", "perditio"],
  limus: ["victus", "aqua"],
  herba: ["victus", "terra"],
  arbor: ["aer", "herba"],
  bestia: ["motus", "victus"],
  corpus: ["mortuus", "bestia"],
  exanimis: ["motus", "mortuus"],
  cognitio: ["ignis", "spiritus"],
  sensus: ["aer", "spiritus"],
  humanus: ["bestia", "cognitio"],
  messis: ["herba", "humanus"],
  perfodio: ["humanus", "terra"],
  instrumentum: ["humanus", "ordo"],
  meto: ["messis", "instrumentum"],
  telum: ["instrumentum", "ignis"],
  tutamen: ["instrumentum", "terra"],
  fames: ["victus", "vacuos"],
  lucrum: ["humanus", "fames"],
  fabrico: ["humanus", "instrumentum"],
  pannus: ["instrumentum", "bestia"],
  machina: ["motus", "instrumentum"],
  vinculum: ["motus", "perditio"],
  tempestas: ["aer", "aqua"],
  tempus: ["vacuos", "ordo"],
  gula: ["fames", "vacuos"],
  infernus: ["ignis", "praecantatio"],
  ira: ["telum", "ignis"],
  luxuria: ["corpus", "fames"],
  superbia: ["volatus", "vacuos"],
  desidia: ["vinculum", "spiritus"],
  invidia: ["sensus", "fames"],
  terminus: ["lucrum", "alienis"],
};


export const ASPECT_RECIPES = {
  ...FULL_ASPECT_RECIPES
};

export const ALL_ASPECTS =
    Object.keys(ASPECT_RECIPES).sort();